package ComputerLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Chasis {
  Midi_Tower("Midi Tower", "Midi Tower"),
  Mini_Tower("Mini Tower", "Mini Tower"),
  Full_Tower("Full Tower", "Full Tower");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private Chasis(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<Chasis> getConstants() {
    List<Chasis> list = ListSequence.fromList(new LinkedList<Chasis>());
    ListSequence.fromList(list).addElement(Chasis.Midi_Tower);
    ListSequence.fromList(list).addElement(Chasis.Mini_Tower);
    ListSequence.fromList(list).addElement(Chasis.Full_Tower);
    return list;
  }
  public static Chasis getDefault() {
    return Chasis.Midi_Tower;
  }
  public static Chasis parseValue(String value) {
    if (value == null) {
      return Chasis.getDefault();
    }
    if (value.equals(Chasis.Midi_Tower.getValueAsString())) {
      return Chasis.Midi_Tower;
    }
    if (value.equals(Chasis.Mini_Tower.getValueAsString())) {
      return Chasis.Mini_Tower;
    }
    if (value.equals(Chasis.Full_Tower.getValueAsString())) {
      return Chasis.Full_Tower;
    }
    return Chasis.getDefault();
  }
}
