package ComputerLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum DataLinkLayer {
  IEEE_802_11b("IEEE-802.11b", "IEEE-802.11b"),
  IEEE_802_11n("IEEE-802.11n", "IEEE-802.11n"),
  IEEE_802_11a("IEEE-802.11a", "IEEE-802.11a"),
  IEEE_802_11g("IEEE-802.11g", "IEEE-802.11g"),
  IEEE_802_11ac("IEEE-802.11ac", "IEEE-802.11ac"),
  IEEE_802_11_SuperG("IEEE-802.11-SuperG", "IEEE-802.11-SuperG");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private DataLinkLayer(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<DataLinkLayer> getConstants() {
    List<DataLinkLayer> list = ListSequence.fromList(new LinkedList<DataLinkLayer>());
    ListSequence.fromList(list).addElement(DataLinkLayer.IEEE_802_11b);
    ListSequence.fromList(list).addElement(DataLinkLayer.IEEE_802_11n);
    ListSequence.fromList(list).addElement(DataLinkLayer.IEEE_802_11a);
    ListSequence.fromList(list).addElement(DataLinkLayer.IEEE_802_11g);
    ListSequence.fromList(list).addElement(DataLinkLayer.IEEE_802_11ac);
    ListSequence.fromList(list).addElement(DataLinkLayer.IEEE_802_11_SuperG);
    return list;
  }
  public static DataLinkLayer getDefault() {
    return null;
  }
  public static DataLinkLayer parseValue(String value) {
    if (value == null) {
      return DataLinkLayer.getDefault();
    }
    if (value.equals(DataLinkLayer.IEEE_802_11b.getValueAsString())) {
      return DataLinkLayer.IEEE_802_11b;
    }
    if (value.equals(DataLinkLayer.IEEE_802_11n.getValueAsString())) {
      return DataLinkLayer.IEEE_802_11n;
    }
    if (value.equals(DataLinkLayer.IEEE_802_11a.getValueAsString())) {
      return DataLinkLayer.IEEE_802_11a;
    }
    if (value.equals(DataLinkLayer.IEEE_802_11g.getValueAsString())) {
      return DataLinkLayer.IEEE_802_11g;
    }
    if (value.equals(DataLinkLayer.IEEE_802_11ac.getValueAsString())) {
      return DataLinkLayer.IEEE_802_11ac;
    }
    if (value.equals(DataLinkLayer.IEEE_802_11_SuperG.getValueAsString())) {
      return DataLinkLayer.IEEE_802_11_SuperG;
    }
    return DataLinkLayer.getDefault();
  }
}
