package ComputerLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum FormFactor {
  ATX("ATX", "1"),
  EATX("EATX", "2"),
  Micro_ATX("Micro-ATX", "3"),
  DTX("DTX", "4"),
  FLEX_ATX("FLEX-ATX", "5"),
  Mini_ITX("Mini-ITX", "6");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private FormFactor(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<FormFactor> getConstants() {
    List<FormFactor> list = ListSequence.fromList(new LinkedList<FormFactor>());
    ListSequence.fromList(list).addElement(FormFactor.ATX);
    ListSequence.fromList(list).addElement(FormFactor.EATX);
    ListSequence.fromList(list).addElement(FormFactor.Micro_ATX);
    ListSequence.fromList(list).addElement(FormFactor.DTX);
    ListSequence.fromList(list).addElement(FormFactor.FLEX_ATX);
    ListSequence.fromList(list).addElement(FormFactor.Mini_ITX);
    return list;
  }
  public static FormFactor getDefault() {
    return FormFactor.ATX;
  }
  public static FormFactor parseValue(String value) {
    if (value == null) {
      return FormFactor.getDefault();
    }
    if (value.equals(FormFactor.ATX.getValueAsString())) {
      return FormFactor.ATX;
    }
    if (value.equals(FormFactor.EATX.getValueAsString())) {
      return FormFactor.EATX;
    }
    if (value.equals(FormFactor.Micro_ATX.getValueAsString())) {
      return FormFactor.Micro_ATX;
    }
    if (value.equals(FormFactor.DTX.getValueAsString())) {
      return FormFactor.DTX;
    }
    if (value.equals(FormFactor.FLEX_ATX.getValueAsString())) {
      return FormFactor.FLEX_ATX;
    }
    if (value.equals(FormFactor.Mini_ITX.getValueAsString())) {
      return FormFactor.Mini_ITX;
    }
    return FormFactor.getDefault();
  }
}
