package ComputerLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum GPUName {
  EVGA_GeForce_GTX_1080_Ti_Founders_Edition("EVGA GeForce GTX 1080 Ti Founders Edition", "EVGA GeForce GTX 1080"),
  Asus_ROG_STRIX_GTX_1080("Asus ROG STRIX GTX 1080", "Asus ROG STRIX GTX 1080"),
  AMD_Radeon_RX_Vega_64_8GB("AMD Radeon RX Vega 64 8GB", "AMD Radeon RX Vega"),
  MSI_GeForce_GTX_1070_GAMING_X_8G("MSI GeForce GTX 1070 GAMING X 8G", "MSI GeForce GTX 1070"),
  Zotac_GeForce_GTX_1050_Ti_4GB_OC_Edition("Zotac GeForce GTX 1050 Ti 4GB OC Edition", "Zotac GeForce GTX 1050"),
  Nvidia_GeForce_GTX_1060_Founders_Edition("Nvidia GeForce GTX 1060 Founders Edition", "Nvidia GeForce GTX 1060"),
  Asus_ROG_Strix_Radeon_RX_580_TOP_Edition_8GB("Asus ROG Strix Radeon RX 580 TOP Edition 8GB", "Asus ROG Strix Radeon RX 580");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private GPUName(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<GPUName> getConstants() {
    List<GPUName> list = ListSequence.fromList(new LinkedList<GPUName>());
    ListSequence.fromList(list).addElement(GPUName.EVGA_GeForce_GTX_1080_Ti_Founders_Edition);
    ListSequence.fromList(list).addElement(GPUName.Asus_ROG_STRIX_GTX_1080);
    ListSequence.fromList(list).addElement(GPUName.AMD_Radeon_RX_Vega_64_8GB);
    ListSequence.fromList(list).addElement(GPUName.MSI_GeForce_GTX_1070_GAMING_X_8G);
    ListSequence.fromList(list).addElement(GPUName.Zotac_GeForce_GTX_1050_Ti_4GB_OC_Edition);
    ListSequence.fromList(list).addElement(GPUName.Nvidia_GeForce_GTX_1060_Founders_Edition);
    ListSequence.fromList(list).addElement(GPUName.Asus_ROG_Strix_Radeon_RX_580_TOP_Edition_8GB);
    return list;
  }
  public static GPUName getDefault() {
    return GPUName.EVGA_GeForce_GTX_1080_Ti_Founders_Edition;
  }
  public static GPUName parseValue(String value) {
    if (value == null) {
      return GPUName.getDefault();
    }
    if (value.equals(GPUName.EVGA_GeForce_GTX_1080_Ti_Founders_Edition.getValueAsString())) {
      return GPUName.EVGA_GeForce_GTX_1080_Ti_Founders_Edition;
    }
    if (value.equals(GPUName.Asus_ROG_STRIX_GTX_1080.getValueAsString())) {
      return GPUName.Asus_ROG_STRIX_GTX_1080;
    }
    if (value.equals(GPUName.AMD_Radeon_RX_Vega_64_8GB.getValueAsString())) {
      return GPUName.AMD_Radeon_RX_Vega_64_8GB;
    }
    if (value.equals(GPUName.MSI_GeForce_GTX_1070_GAMING_X_8G.getValueAsString())) {
      return GPUName.MSI_GeForce_GTX_1070_GAMING_X_8G;
    }
    if (value.equals(GPUName.Zotac_GeForce_GTX_1050_Ti_4GB_OC_Edition.getValueAsString())) {
      return GPUName.Zotac_GeForce_GTX_1050_Ti_4GB_OC_Edition;
    }
    if (value.equals(GPUName.Nvidia_GeForce_GTX_1060_Founders_Edition.getValueAsString())) {
      return GPUName.Nvidia_GeForce_GTX_1060_Founders_Edition;
    }
    if (value.equals(GPUName.Asus_ROG_Strix_Radeon_RX_580_TOP_Edition_8GB.getValueAsString())) {
      return GPUName.Asus_ROG_Strix_Radeon_RX_580_TOP_Edition_8GB;
    }
    return GPUName.getDefault();
  }
}
