package ComputerLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum HDDName {
  WD_Blue_1TB("WD Blue 1TB", "WD Blue"),
  Toshiba_P300_3TB("Toshiba P300 3TB", "Toshiba P300"),
  Seagate_IronWolf_10TB("Seagate IronWolf 10TB", "Seagate IronWolf");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private HDDName(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<HDDName> getConstants() {
    List<HDDName> list = ListSequence.fromList(new LinkedList<HDDName>());
    ListSequence.fromList(list).addElement(HDDName.WD_Blue_1TB);
    ListSequence.fromList(list).addElement(HDDName.Toshiba_P300_3TB);
    ListSequence.fromList(list).addElement(HDDName.Seagate_IronWolf_10TB);
    return list;
  }
  public static HDDName getDefault() {
    return HDDName.WD_Blue_1TB;
  }
  public static HDDName parseValue(String value) {
    if (value == null) {
      return HDDName.getDefault();
    }
    if (value.equals(HDDName.WD_Blue_1TB.getValueAsString())) {
      return HDDName.WD_Blue_1TB;
    }
    if (value.equals(HDDName.Toshiba_P300_3TB.getValueAsString())) {
      return HDDName.Toshiba_P300_3TB;
    }
    if (value.equals(HDDName.Seagate_IronWolf_10TB.getValueAsString())) {
      return HDDName.Seagate_IronWolf_10TB;
    }
    return HDDName.getDefault();
  }
}
