package ComputerLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CentralProcessingUnit = 0;
  public static final int Component = 1;
  public static final int ComputerCase = 2;
  public static final int GPUWrapper = 3;
  public static final int GamesList = 4;
  public static final int GraphicsCard = 5;
  public static final int HDDWrapper = 6;
  public static final int HardDrive = 7;
  public static final int MotherBoard = 8;
  public static final int PC = 9;
  public static final int PCCooling = 10;
  public static final int PowerSupply = 11;
  public static final int RAMWrapper = 12;
  public static final int RandomAccessMemory = 13;
  public static final int SSDWrapper = 14;
  public static final int SolidStateDrive = 15;
  public static final int User = 16;
  public static final int WirelessNetworkAdapter = 17;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf4582f1691744942L, 0x8b09d4f72a7da258L);
    builder.put(0x58d6939bef858273L, CentralProcessingUnit);
    builder.put(0x2869488cfc48eec9L, Component);
    builder.put(0x55289da3a626ef92L, ComputerCase);
    builder.put(0x853c707cd6c1ed4L, GPUWrapper);
    builder.put(0x6c32b212dc9748adL, GamesList);
    builder.put(0x58d6939bef858269L, GraphicsCard);
    builder.put(0x853c707cd6c1d59L, HDDWrapper);
    builder.put(0x58d6939bef858264L, HardDrive);
    builder.put(0x55289da3a626f077L, MotherBoard);
    builder.put(0x2869488cfc48ee90L, PC);
    builder.put(0xbc500a6864c3a83L, PCCooling);
    builder.put(0x55289da3a626f174L, PowerSupply);
    builder.put(0x9d797225990c617L, RAMWrapper);
    builder.put(0x58d6939bef858288L, RandomAccessMemory);
    builder.put(0x853c707cd67310eL, SSDWrapper);
    builder.put(0x58d6939bef857e98L, SolidStateDrive);
    builder.put(0x6c32b212dc9746b0L, User);
    builder.put(0x58d6939bef858292L, WirelessNetworkAdapter);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
