package ComputerLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum MotherBoardName {
  Gigabyte_Aorus_Z270X_Gaming_9("Gigabyte Aorus Z270X-Gaming 9", "Gigabyte Aorus Z270X-Gaming"),
  ASRock_Z270_Killer_SLI_ac("ASRock Z270 Killer SLI/ac", "ASRock Z270 Killer SLI/ac"),
  ASUS_RoG_Maximus_IX_Hero("ASUS RoG Maximus IX Hero", "ASUS RoG Maximus IX Hero"),
  Biostar_Racing_Z270GT9("Biostar Racing Z270GT9", "Biostar Racing"),
  MSI_Z270_SLI_Plus("MSI Z270 SLI Plus", "MSI Z270 SLI Plus"),
  ASRock_Z270_Gaming_ITX_ac("ASRock Z270 Gaming-ITX/ac", "ASRock Z270 Gaming-ITX/ac"),
  ECS_Z270H4_I("ECS Z270H4-I", "ECS Z270H4-I");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private MotherBoardName(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<MotherBoardName> getConstants() {
    List<MotherBoardName> list = ListSequence.fromList(new LinkedList<MotherBoardName>());
    ListSequence.fromList(list).addElement(MotherBoardName.Gigabyte_Aorus_Z270X_Gaming_9);
    ListSequence.fromList(list).addElement(MotherBoardName.ASRock_Z270_Killer_SLI_ac);
    ListSequence.fromList(list).addElement(MotherBoardName.ASUS_RoG_Maximus_IX_Hero);
    ListSequence.fromList(list).addElement(MotherBoardName.Biostar_Racing_Z270GT9);
    ListSequence.fromList(list).addElement(MotherBoardName.MSI_Z270_SLI_Plus);
    ListSequence.fromList(list).addElement(MotherBoardName.ASRock_Z270_Gaming_ITX_ac);
    ListSequence.fromList(list).addElement(MotherBoardName.ECS_Z270H4_I);
    return list;
  }
  public static MotherBoardName getDefault() {
    return MotherBoardName.Gigabyte_Aorus_Z270X_Gaming_9;
  }
  public static MotherBoardName parseValue(String value) {
    if (value == null) {
      return MotherBoardName.getDefault();
    }
    if (value.equals(MotherBoardName.Gigabyte_Aorus_Z270X_Gaming_9.getValueAsString())) {
      return MotherBoardName.Gigabyte_Aorus_Z270X_Gaming_9;
    }
    if (value.equals(MotherBoardName.ASRock_Z270_Killer_SLI_ac.getValueAsString())) {
      return MotherBoardName.ASRock_Z270_Killer_SLI_ac;
    }
    if (value.equals(MotherBoardName.ASUS_RoG_Maximus_IX_Hero.getValueAsString())) {
      return MotherBoardName.ASUS_RoG_Maximus_IX_Hero;
    }
    if (value.equals(MotherBoardName.Biostar_Racing_Z270GT9.getValueAsString())) {
      return MotherBoardName.Biostar_Racing_Z270GT9;
    }
    if (value.equals(MotherBoardName.MSI_Z270_SLI_Plus.getValueAsString())) {
      return MotherBoardName.MSI_Z270_SLI_Plus;
    }
    if (value.equals(MotherBoardName.ASRock_Z270_Gaming_ITX_ac.getValueAsString())) {
      return MotherBoardName.ASRock_Z270_Gaming_ITX_ac;
    }
    if (value.equals(MotherBoardName.ECS_Z270H4_I.getValueAsString())) {
      return MotherBoardName.ECS_Z270H4_I;
    }
    return MotherBoardName.getDefault();
  }
}
