package ComputerLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum PSUName {
  Corsair_RM750x("Corsair RM750x", "Corsair RM750x"),
  EVGA_500_B1("EVGA 500 B1", "EVGA 500 B1"),
  be_quiet__Straight_Power_10("be quiet! Straight Power 10", "be quiet! Straight Power 10");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private PSUName(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<PSUName> getConstants() {
    List<PSUName> list = ListSequence.fromList(new LinkedList<PSUName>());
    ListSequence.fromList(list).addElement(PSUName.Corsair_RM750x);
    ListSequence.fromList(list).addElement(PSUName.EVGA_500_B1);
    ListSequence.fromList(list).addElement(PSUName.be_quiet__Straight_Power_10);
    return list;
  }
  public static PSUName getDefault() {
    return PSUName.Corsair_RM750x;
  }
  public static PSUName parseValue(String value) {
    if (value == null) {
      return PSUName.getDefault();
    }
    if (value.equals(PSUName.Corsair_RM750x.getValueAsString())) {
      return PSUName.Corsair_RM750x;
    }
    if (value.equals(PSUName.EVGA_500_B1.getValueAsString())) {
      return PSUName.EVGA_500_B1;
    }
    if (value.equals(PSUName.be_quiet__Straight_Power_10.getValueAsString())) {
      return PSUName.be_quiet__Straight_Power_10;
    }
    return PSUName.getDefault();
  }
}
