package ComputerLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum SSDName {
  Crucial_MX300("Crucial MX300", "Crucial MX300"),
  Apacer_Armor_AS681("Apacer Armor AS681", "Apacer Armor AS681"),
  WD_Blue_SSD("WD Blue SSD", "WD Blue SSD"),
  Toshiba_OCZ_VX500("Toshiba OCZ VX500", "Toshiba OCZ VX500"),
  Samsung_SSD_850_Pro("Samsung SSD 850 Pro", "Samsung SSD 850 Pro"),
  Kingston_SSDNow("Kingston SSDNow", "Kingston SSDNow");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private SSDName(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<SSDName> getConstants() {
    List<SSDName> list = ListSequence.fromList(new LinkedList<SSDName>());
    ListSequence.fromList(list).addElement(SSDName.Crucial_MX300);
    ListSequence.fromList(list).addElement(SSDName.Apacer_Armor_AS681);
    ListSequence.fromList(list).addElement(SSDName.WD_Blue_SSD);
    ListSequence.fromList(list).addElement(SSDName.Toshiba_OCZ_VX500);
    ListSequence.fromList(list).addElement(SSDName.Samsung_SSD_850_Pro);
    ListSequence.fromList(list).addElement(SSDName.Kingston_SSDNow);
    return list;
  }
  public static SSDName getDefault() {
    return SSDName.Crucial_MX300;
  }
  public static SSDName parseValue(String value) {
    if (value == null) {
      return SSDName.getDefault();
    }
    if (value.equals(SSDName.Crucial_MX300.getValueAsString())) {
      return SSDName.Crucial_MX300;
    }
    if (value.equals(SSDName.Apacer_Armor_AS681.getValueAsString())) {
      return SSDName.Apacer_Armor_AS681;
    }
    if (value.equals(SSDName.WD_Blue_SSD.getValueAsString())) {
      return SSDName.WD_Blue_SSD;
    }
    if (value.equals(SSDName.Toshiba_OCZ_VX500.getValueAsString())) {
      return SSDName.Toshiba_OCZ_VX500;
    }
    if (value.equals(SSDName.Samsung_SSD_850_Pro.getValueAsString())) {
      return SSDName.Samsung_SSD_850_Pro;
    }
    if (value.equals(SSDName.Kingston_SSDNow.getValueAsString())) {
      return SSDName.Kingston_SSDNow;
    }
    return SSDName.getDefault();
  }
}
