package ComputerLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class GamesList_Constraints extends BaseConstraintsDescriptor {
  public GamesList_Constraints() {
    super(MetaAdapterFactory.getConcept(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, "ComputerLanguage.structure.GamesList"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x6c32b212dc97492aL, "game"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x6c32b212dc97492aL), this) {
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "game";
        SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x6c32b212dc97492aL, "game"), (SPropertyOperations.getString(propertyValue)));
        if ((SPropertyOperations.getString(propertyValue)).equals("League of Legends")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (12));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (2));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (1));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (346));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Hearthstone")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (20));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (4));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (1));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (346));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Dota 2")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (15));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (6));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (4));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (139));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Overwatch")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (5));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (2));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (1));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (1882));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Counter-Strike: Global Offensive")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (8));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (2));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (3));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (311));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Elder Scrolls Online")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (60));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (6));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (5));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (346));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("GTA 5")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (65));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (8));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (7));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (336));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("H1Z1 King of the Kill")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (20));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (2));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (1));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (1089));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Minecraft")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (1));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (2));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (6));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (208));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Battlefield 1")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7faL, "min_HDD_space"), "" + (50));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7ffL, "min_RAM"), "" + (16));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7f6L, "min_cpu_performance"), "" + (8));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x6c32b212dc9748adL, 0x23a44d5238bef7d8L, "min_gpu_gflops"), "" + (4000));
        }
      }
    });
    return properties;
  }
}
