package ComputerLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class GraphicsCard_Constraints extends BaseConstraintsDescriptor {
  public GraphicsCard_Constraints() {
    super(MetaAdapterFactory.getConcept(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, "ComputerLanguage.structure.GraphicsCard"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL), this) {
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "gpuName";
        SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), (SPropertyOperations.getString(propertyValue)));
        if ((SPropertyOperations.getString(propertyValue)).equals("EVGA GeForce GTX 1080")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1480));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (11));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (11300));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Asus ROG STRIX GTX 1080")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1607));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (8));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (8800));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("AMD Radeon RX Vega")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1247));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (8));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (13700));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("MSI GeForce GTX 1070")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1506));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (8));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (6801));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Zotac GeForce GTX 1050")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1290));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (4));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (2313));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Nvidia GeForce GTX 1060")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1506));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (3));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (4372));
        } else if ((SPropertyOperations.getString(propertyValue)).equals("Asus ROG Strix Radeon RX 580")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1257));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (8));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (6267));
        }
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL), this) {
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "clockSpeed";
        // these values are base clocks. 
        if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("EVGA GeForce GTX 1080")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1480));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Asus ROG STRIX GTX 1080")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1607));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("AMD Radeon RX Vega")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1247));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("MSI GeForce GTX 1070")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1506));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Zotac GeForce GTX 1050")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1290));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Nvidia GeForce GTX 1060")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1506));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Asus ROG Strix Radeon RX 580")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826aL, "clockSpeed"), "" + (1257));
        }
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL), this) {
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "memoryGB";
        if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("EVGA GeForce GTX 1080")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (11));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Asus ROG STRIX GTX 1080")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (8));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("AMD Radeon RX Vega")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (8));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("MSI GeForce GTX 1070")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (8));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Zotac GeForce GTX 1050")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (4));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Nvidia GeForce GTX 1060")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (3));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Asus ROG Strix Radeon RX 580")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826cL, "memoryGB"), "" + (8));
        }
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL), this) {
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "gflops";
        // these are double precision GFLOP figures. 
        if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("EVGA GeForce GTX 1080")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (11300));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Asus ROG STRIX GTX 1080")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (8800));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("AMD Radeon RX Vega")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (13700));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("MSI GeForce GTX 1070")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (6801));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Zotac GeForce GTX 1050")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (2313));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Nvidia GeForce GTX 1060")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (4372));
        } else if (SPropertyOperations.getString_def(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x7c6dc1906f8efeaeL, "gpuName"), "EVGA GeForce GTX 1080").equals("Asus ROG Strix Radeon RX 580")) {
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xf4582f1691744942L, 0x8b09d4f72a7da258L, 0x58d6939bef858269L, 0x58d6939bef85826fL, "gflops"), "" + (6267));
        }
      }
    });
    return properties;
  }
}
